openapi: 3.0.1
info:
  title: Currency rates api
  description: This  api provides actual currency rates
  version: v0.0.1
externalDocs:
  description: You can find a source code here
  url: https://github.com/Turatov/CurrencyRates
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/currencies:
    get:
      tags:
      - currency-controller
      summary: 'Get a list of actual rates for currencies '
      description: Returns a list of currencies
      operationId: getAllCurrencies
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
    put:
      tags:
      - currency-controller
      summary: 'Update a currency by code '
      description: "If exist will update, if is not will add "
      operationId: updateCurrencyByCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Currency'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Currency'
    post:
      tags:
      - currency-controller
      summary: Add new currency
      operationId: addCurrency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrencyAddingRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/schedule:
    post:
      tags:
      - schedule-controller
      summary: Schedule currency rate
      description: Send json with new rate and datetime to schedule rates
      operationId: scheduleJob
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduledCurrencyDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/schedule/jobs:
    get:
      tags:
      - schedule-controller
      summary: Get scheduled jobs
      description: Returns list of active jobs
      operationId: getAllJobs
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /api/currencies/{code}:
    get:
      tags:
      - currency-controller
      summary: Get a currency by code
      description: 'Returns a currency by code '
      operationId: getCurrencyByCode
      parameters:
      - name: code
        in: path
        description: Currency code to be  retrieved
        required: true
        schema:
          type: string
        example: USD
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Currency'
components:
  schemas:
    Currency:
      type: object
      properties:
        code:
          type: string
          description: Unique identifier of the currency
          example: USD
        rate:
          type: number
          description: 'Currency rate '
          format: double
          example: 90.8
    ScheduledCurrencyDTO:
      type: object
      properties:
        datetime:
          type: string
          description: Trigger time to schedule with time zone
          format: date-time
          example: 2024-08-08T19:37:00.259Z
        data:
          type: object
          additionalProperties:
            type: number
            description: Array for currencies
            format: double
          description: Array for currencies
          example:
            USD: "98.2"
    CurrencyAddingRequest:
      type: object
      properties:
        currency:
          $ref: '#/components/schemas/Currency'
